---
- hosts: mentorbot
  remote_user: ubuntu
  become: yes

  vars_prompt:
    - name: "gh_user"
      prompt: "Enter GitHub username"
      private: no

    - name: "gh_pass"
      prompt: "Enter GitHub password"

  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: latest
      with_items:
        - make
        - build-essential
        - libexpat1-dev
        - zlib1g-dev
        - libxml2-dev
        - git

    - name: Download cpanminus
      get_url:
        url: http://cpanmin.us
        dest: /tmp/cpanm.pl
        mode: 0755

    - name: Install cpanminus
      command: perl cpanm.pl App::cpanminus
      args:
        chdir: /tmp/
        creates: /usr/local/bin/cpanm

    - name: Install bot
      cpanm:
        name: Bot::BasicBot::Pluggable

    - name: Generate SSH key
      user:
        name: ubuntu
        generate_ssh_key: yes
      register: ssh_key

    - name: Get public key contents
      shell: cat /home/ubuntu/.ssh/id_rsa.pub
      register: pub_key
      when: ssh_key.changed

    - name: Upload SSH key to GitHub
      uri:
        url: https://api.github.com/user/keys
        method: POST
        body_format: json
        body: "{ \"key\": \"{{ pub_key.stdout }}\"}"
        user: "{{ gh_user }}"
        password: "{{ gh_pass }}"
        force_basic_auth: yes
        status_code: 201,422
      when: ssh_key.changed

    - name: Clone Mentorbot project
      become_user: ubuntu
      git:
        repo: git@github.com:zendoodles/mentorbot.git
        dest: /home/ubuntu/mentorbot
        accept_hostkey: true
        update: no

    - name: Create startup script
      copy:
        src: files/mentorbot.init
        dest: /etc/init.d/mentorbot
        mode: 0755

    - name: Start mentorbot
      service:
        name: mentorbot
        enabled: yes
        state: started
